language: ruby
rvm:
- 2.3.0
before_install: gem install bundler -v 1.11.2
env:
  global:
    secure: nWIde7eQEFDcalkJl01JR2lHBBycuc/jQIHaJK4GUA5pbBTXRTSzVdichBbpTktISRfnosSWEjRVLwu/EGPnBbJPFegtIBrDb4NXhVaAm0rr3gk22PDxT77ea2oEyozYmfsqIdVa4CXPDhRsjJEr5rH6Qxk8BHSTRJPx8LfxEDhmP5c/Yfkk0DVMt6bsVPNuRZjUNJNDn74aKSXxgAMt+crAFNtxM8D9FkB9xYwxqrltfK9Sk4wZEwfpossnAtzr/2DISOeQfBNtJrWCp0FDkyRBpku84EQkGdU7VKvWnjQXh4tFfdm3g647Z3v5ZgwuVuZ6ahtR+36IO7OA4ICj+BpLHJK0X3Pvflx2D/TDljvi0lIoW3iY1EbepG7WZcw72Z2twlDGhrrkqov+G3qHADDDJuQ+qhJrU1VPIJFLK9a0MSS2E5xFegTFIUBNecXQo22bieXL1cnCKg8/HeWac/mqt0SBBUh5Rb3LoieifognChV4nxePdZKsMZrYC5Yffgd093cIi+KDKIFTPIkRNJRDyN26Or8FeRTA103wWWdoOIHBL0/yGPs/xaz2rsQ9YWKAcIp96NHP2Lr1SH972BnQBJUeVLVjW3BGsK7fwVP/FLuKb2oLFCWtbspc2SqRRmq1RTx4oJ/Oso9XfpHZ+zijd4WSXeM5ghiDlXhjXu0=
