language: ruby
rvm:
- 2.3.0
before_install: gem install bundler -v 1.11.2
env:
  global:
    secure: "vMsO3yrLFu3tqCBKzPFDGTAbXVOu2XZht5KTTm21KfeIb1hWcxeRAkS3ajZ/cKSOO/j5vQ/u7QiQc00DP+x3hhuJ6TB9yADrCklR+dd+X+UCoOxZgvFS8oMvq5S+BKC34ANKlCzhrgX40N4k+4arDGPvaZbyQV7W3SfZlVtCi+47/4yuNZFtIyG+SboQHWedroxvOdGQMcvNq+FVrR5RbA8V0DMhprLL7668p1iw0NCIJAaPuAA+l+PIlVfCwBnlC+BUJzsPRy2r64ZG+MSMJe5PARBCO091UYdfPnMuTu3spsS9K4/GbWO2Ko5yhVBJDzI1oUr7eiGA6FhdJvO4m5J8TlLMdHDYD+sTE9U6Nc1Oz+2iifTY/Rrq6tgudIdJPlwtiK6V+FRg2nRwqoXtXbdOetdceD7UOmS13if6y3tDAdEViJ/podHvWHC+bGuRR/sXsPV+BcvOawD5bggIzT/iCVLLZzRdTn4xg2lZ9P0wKhi7kIDBbbeySqw8+wUqtU6/WrmtQE/OBzFkh/nm6m03KuId62IDS5jiM+RQKGf1ZeDT7P5AmNW4x4w3uvnT97iW/2N5mkBtfUa1+bjFtONiITRoWEX4TFnnHPYIorf+YQvrOH/OaD2uRr7A6nEO5ovx7Q6TvA6rBBAAOh+t0QsxvOYZnVR2XLAenpt0pYY="
